name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
        os:
          - ubuntu-latest
          - centos:7.4.1708
          - centos:7.6.1810
          - centos:7.7.1908
          - centos:7.8.2003
          - centos:7.9.2009
          - ubuntu:18.04
          - ubuntu:20.04
          - ubuntu:22.04
          - fedora:35
          - fedora:36
          - debian:10
          - debian:11
    container: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: GNU Create Package
        if: matrix.os == 'ubuntu-latest'
        run: .github/scripts/package.sh
        shell: bash
      - name: OS Create Package
        if: matrix.os != 'ubuntu-latest'
        run: |
          tgtname=$(echo ${{ matrix.os }} | tr -d ':')
          .github/scripts/package.sh $tgtname;
        shell: bash
      - name: Get Artifact Name
        run: |
          ARTIFACT_PATHNAME=$(ls ./bender-*.tar.gz | head -n 1)
          ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
          echo "ARTIFACT_PATHNAME=${ARTIFACT_PATHNAME}" >> $GITHUB_ENV
        shell: bash
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ARTIFACT_PATHNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
