name: release

# on:
#   release:
#     types: [created]

on:
  push:
    branches: [ test_actions ]
  pull_request:
    branches: [ test_actions ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    env:
      PKG_OS: "centos:7.4.1708 centos:7.6.1810 centos:7.7.1908 centos:7.8.2003 centos:8.1.1911 centos:8.2.2004 ubuntu:16.04 ubuntu:18.04 ubuntu:20.04 ubuntu:20.10"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust}}
          override: true
          components: rustfmt
      - name: Release Build
        run: cargo build --release
      - name: All OSes
        run: |
          for os in $env.PKG_OS; do
            tgtname=$(echo $os | tr -d ':')
            docker run 
              -t --rm
              -v "$PWD:/source"
              -v "$PWD/target/$tgtname:/source/target"
              accuminium/rust-${os}_stable
              cargo build --release;
          done
      # - run: .github/scripts/package.sh
      #   shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: bender_builds
          path: target/
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path:

