name: release

# on:
#   release:
#     types: [created]

on:
  push:
    branches: [ test_actions ]
  pull_request:
    branches: [ test_actions ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    env:
      PKG_OS: "centos:7.4.1708"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust}}
          override: true
          components: rustfmt
      - name: Release Build
        run: cargo build --release
      - name: All OSes
        run: |
          for os in $env.PKG_OS; do
            echo $os
            export tgtname=$(echo $os | tr -d ':')
            docker run \
              -t --rm \
              -v "$GITHUB_WORKSPACE:/source" \
              -v "$GITHUB_WORKSPACE/target/$tgtname:/source/target" \
              accuminium/rust-${os}_stable \
              cargo build --release;
          done
      # - run: .github/scripts/package.sh
      #   shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: bender_builds
          path: target/
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path:

